kiial_papers/urls.py
"""
kiial_papers URL Configuration
"""
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib import admin
from django.urls import path,include
from django_filters.views import FilterView
from papers.filters import PapersFilter
from papers.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('papers.urls', namespace="papers")),
    url(r'^search/$', FilterView.as_view(filterset_class=PapersFilter,
        template_name='papers/search.html'), name='search'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path("convert/", include("guest_user.urls")),
]

papers/urls.py
from django.urls import path
from .views import (
    IndexListView,
    PaperListView,
    PaperDetailView,
    PaperCreateView,
    PaperUpdateView,
    PaperDeleteView,
    ResearcherListView,
    ResearcherDetailView,
    ResearcherCreateView,
    ResearcherUpdateView,
    ResearcherDeleteView,
    SupervisorListView,
    SupervisorDetailView,
    SupervisorCreateView,
    SupervisorUpdateView,
    SupervisorDeleteView,
)

app_name = "papers"

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('papers/', PaperListView.as_view(), name='papers_list'),
    path('paper/<int:pk>/', PaperDetailView.as_view(), name='paper_detail'),
    path('create/paper/', PaperCreateView.as_view(), name='create_paper'),
    path('update/paper/<int:pk>/', PaperUpdateView.as_view(), name='update_paper'),
    path('delete/paper/<int:pk>/', PaperDeleteView.as_view(), name='delete_paper'),
    path('researchers/', ResearcherListView.as_view(), name='researchers_list'),
    path('researcher/<int:pk>/', ResearcherDetailView.as_view(), name='researcher_detail'),
    path('create/researcher/', ResearcherCreateView.as_view(), name='create_researcher'),
    path('update/researcher/<int:pk>/', ResearcherUpdateView.as_view(), name='update_researcher'),
    path('delete/researcher/<int:pk>/', ResearcherDeleteView.as_view(), name='delete_researcher'),
    path('supervisors/', SupervisorListView.as_view(), name='supervisors_list'),
    path('supervisor/<int:pk>/', SupervisorDetailView.as_view(), name='supervisor_detail'),
    path('create/supervisor/', SupervisorCreateView.as_view(), name='create_supervisor'),
    path('update/supervisor/<int:pk>/', SupervisorUpdateView.as_view(), name='update_supervisor'),
    path('delete/supervisor/<int:pk>/', SupervisorDeleteView.as_view(), name='delete_supervisor'),
#    path('<int:pk>',.as_view(), name='papers-details'),
]

templates/partials/footer.html
{% load static %}

<!--===== FOOTER =====-->

<footer class="footer">
    <div class="footer__social">
        <a href="#" class="footer__icon"><i class='bx bx-chevrons-up bx-lg'></i></a>
    </div>
    <center>
        <p class="footer__title"><img src="{% static 'img/download.jpg'%}" alt="#"/></p>
    </center>
    <div class="footer__social">
        <a class="footer__icon"  target="_blank" href="https://github.com/almustafa-noureddin"><i class="fa fa-github"></i></a>
            
            <a class="footer__icon"  target="_blank" href="https://twitter.com/almustafa_a_n"><i class="fa fa-twitter"></i></a>
            <a  class="footer__icon"  target="_blank" href="https://www.linkedin.com/in/almustafa-noureddin/"><i class="fa fa-linkedin"></i></a>
                            
        
    </div>
    <p class="footer__copy">Copyright &#169; {% now 'Y' %}. All rigths reserved</p>
</footer>

templates/partials/header.html
{% load static %}
</div>


 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 
 <title>Document</title>
 </head>
 <body>
     
  <!-- Pre-header Starts -->
  <div class="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-8 col-7">
          <ul class="info">
            <li>developed by almustafa noureddin</li>
            <li><a href="#"><i class="fa fa-envelope"></i>almustafanoureddin@gmail.com</a></li>
            
          </ul>
        </div>
        <div class="col-lg-4 col-sm-4 col-5">
          <ul class="social-media">
            <li><a href="https://github.com/almustafa-noureddin"><i class="fa fa-github"></i></a></li>
            
            <li><a href="https://twitter.com/almustafa_a_n"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.linkedin.com/in/almustafa-noureddin/"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- Pre-header End -->
<header>
    <nav class="navbar">
        <!-- LOGO -->
        <a href="{% url 'papers:index' %}" class="logo">
            <img src="{% static 'img/download.jpg'%}" alt="">
          </a>
        <!-- NAVIGATION MENU -->
        <ul class="nav-links">
        <!-- USING CHECKBOX HACK -->
        <input type="checkbox" id="checkbox_toggle" />
        <label for="checkbox_toggle" class="hamburger">&#9776;</label>
       
 <div class="menu">
    

    
    {% if request.user.is_authenticated %}
    تسجيل دخول ك: {{ request.user.username }}
    <li><a href="{% url 'logout' %}">
      تسجيل خروج
        
    </a></li>
  {% else %}
  <li><a href="{% url 'login' %}">
      تسجيل دخول
  </a></li>
  {% endif %}
 {% if not request.user.is_authenticated %}
 <li>
     
    <a href="{% url 'signup' %}" >التسجيل</a>
    
</li>
{% endif %}
 
    <li><a href="{% url 'papers:papers_list' %}">الأوراق العلمية</a></li>
 <li><a href="{% url 'papers:researchers_list' %}">الباحثين</a></li>
 <li><a href="{% url 'papers:supervisors_list' %}">المشرفين</a></li>
 </div>
 </ul>
 </nav>
</header>

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
    <script>alert("{{ message }}")</script>
    {% endfor %}
{% endif %}