kiial_papers/urls.py
"""
kiial_papers URL Configuration
"""
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib import admin
from django.urls import path,include
from django_filters.views import FilterView
from papers.filters import PapersFilter
from papers.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('papers.urls', namespace="papers")),
    url(r'^search/$', FilterView.as_view(filterset_class=PapersFilter,
        template_name='papers/search.html'), name='search'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path("convert/", include("guest_user.urls")),
]

papers/urls.py
from django.urls import path
from .views import (
    IndexListView,
    PaperListView,
    PaperDetailView,
    PaperCreateView,
    PaperUpdateView,
    PaperDeleteView,
    ResearcherListView,
    ResearcherDetailView,
    ResearcherCreateView,
    ResearcherUpdateView,
    ResearcherDeleteView,
    SupervisorListView,
    SupervisorDetailView,
    SupervisorCreateView,
    SupervisorUpdateView,
    SupervisorDeleteView,
)

app_name = "papers"

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('papers/', PaperListView.as_view(), name='papers_list'),
    path('paper/<int:pk>/', PaperDetailView.as_view(), name='paper_detail'),
    path('create/paper/', PaperCreateView.as_view(), name='create_paper'),
    path('update/paper/<int:pk>/', PaperUpdateView.as_view(), name='update_paper'),
    path('delete/paper/<int:pk>/', PaperDeleteView.as_view(), name='delete_paper'),
    path('researchers/', ResearcherListView.as_view(), name='researchers_list'),
    path('researcher/<int:pk>/', ResearcherDetailView.as_view(), name='researcher_detail'),
    path('create/researcher/', ResearcherCreateView.as_view(), name='create_researcher'),
    path('update/researcher/<int:pk>/', ResearcherUpdateView.as_view(), name='update_researcher'),
    path('delete/researcher/<int:pk>/', ResearcherDeleteView.as_view(), name='delete_researcher'),
    path('supervisors/', SupervisorListView.as_view(), name='supervisors_list'),
    path('supervisor/<int:pk>/', SupervisorDetailView.as_view(), name='supervisor_detail'),
    path('create/supervisor/', SupervisorCreateView.as_view(), name='create_supervisor'),
    path('update/supervisor/<int:pk>/', SupervisorUpdateView.as_view(), name='update_supervisor'),
    path('delete/supervisor/<int:pk>/', SupervisorDeleteView.as_view(), name='delete_supervisor'),
#    path('<int:pk>',.as_view(), name='papers-details'),
]

papers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
# Create your models here.

class User(AbstractUser):
    is_organisor = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Researcher(models.Model):
    class Meta:
        verbose_name_plural = 'Researchers'
        verbose_name = 'Researcher'
    
    first_name = models.CharField(max_length=50, blank=True, null=True)
    second_name = models.CharField(max_length=50, blank=True, null=True)
    third_name = models.CharField(max_length=50, blank=True, null=True)
    fourth_name = models.CharField(max_length=50, blank=True, null=True)
    alternative_name = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return f'{self.alternative_name} {self.first_name} {self.second_name} {self.third_name} {self.fourth_name}'


class Degree(models.Model):
    class Meta:
        verbose_name_plural='Degrees'
        verbose_name='Degree'
    
    degree_type = models.CharField(max_length=50, null=True, blank=True)
    
    def __str__(self):
        return self.degree_type

class Supervisor(models.Model):
    class Meta:
        verbose_name_plural='Supervisors'
        verbose_name='Supervisor'
    
    first_name = models.CharField(max_length=20, blank=True, null=True)
    second_name = models.CharField(max_length=20, blank=True, null=True)
    third_name = models.CharField(max_length=20, blank=True, null=True)
    fourth_name = models.CharField(max_length=20, blank=True, null=True)
    alternative_name = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return f'{self.first_name} {self.second_name} {self.third_name} {self.fourth_name}'


class Paper(models.Model):
    class Meta:
        verbose_name_plural = 'Papers'
        verbose_name = 'Paper'
    
    title = models.CharField(max_length=300, blank=True, null=True,verbose_name="العنوان")
    researcher = models.ForeignKey(Researcher, on_delete=models.SET_NULL, blank=True, null=True,verbose_name="الباحث")
    supervisor = models.ManyToManyField(Supervisor, blank=True,verbose_name="المشرف")
    degree = models.ForeignKey(Degree, on_delete=models.SET_NULL, blank=True, null=True,verbose_name="الدرجة العلمية")
    date_of_publishing = models.IntegerField( blank=True, null=True,verbose_name="تاريخ النشر")
    paper_number = models.IntegerField( blank=True, null=True,verbose_name="رقم الورقة")
    other = models.CharField(max_length=200, blank=True, null=True)
    
    
    def __str__(self):
        return self.title


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

#class PaperSupervisor(models.Model):
#    class Meta:
#        verbose_name_plural='PaperSupervisors'
#        verbose_name='PaperSupervisor'
#    
#    paper=models.ForeignKey(Paper,on_delete=models.SET_NULL,null=True,blank=True)
#    supervisor=models.ForeignKey(Supervisor,on_delete=models.SET_NULL,null=True,blank=True)
#    
#    def __str__(self):
#        return f'{self.paper}, {self.supervisor}'

papers/forms.py
from django import forms
from papers.models import Paper, Researcher, Supervisor, User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class PaperModelForm(forms.ModelForm):
    class Meta:
        model = Paper
        fields = (
            'title',
            'researcher',
            'supervisor',
            'degree',
            'date_of_publishing',
            'paper_number',
        )


class ResearcherModelForm(forms.ModelForm):
    class Meta:
        model = Researcher
        fields = (
            'first_name',
            'second_name',
            'third_name',
            'fourth_name',
            'alternative_name',
            'title',
        )


class SupervisorModelForm(forms.ModelForm):
    class Meta:
        model = Supervisor
        fields = (
            'first_name',
            'second_name',
            'third_name',
            'fourth_name',
            'alternative_name',
            'title',
        )






#from django import forms
#
#class SearchForm(forms.ModelForm):
#    name = forms.CharField(max_length=200, required=True,
#		    widget=forms.TextInput(attrs={
#			'placeholder': '*search',
#			'class': 'form-control'
#			}))

papers/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .tables import PaperTable
#from .forms import SearchForm
from .models import (
	Paper,
	Researcher,
    Supervisor,
	
	)
from django.core.paginator import Paginator
from django.views import generic
from django.views.generic.edit import ModelFormMixin
from .filters import PapersFilter
from .forms import PaperModelForm, ResearcherModelForm, SupervisorModelForm, CustomUserCreationForm
from django_tables2 import SingleTableView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.contrib.auth.mixins import LoginRequiredMixin
#from guest_user.mixins import AllowGuestUserMixin
from .mixins import OrganisorAndLoginRequiredMixin
#class IndexView(generic.TemplateView):
#	template_name = "papers/index.html"
#
#	def get_context_data(self, **kwargs):
#		context = super().get_context_data(**kwargs)
#		
#		papers = Paper.objects.all()[:10]
#		researchers = Researcher.objects.all()[:10]
#		papersupervisors = PaperSupervisor.objects.all()
#		degrees = Degree.objects.all()[:10]
#		
#		context["papers"] = papers
#		context["researchers"] = researchers
#		context["papersupervisors"] = papersupervisors
#		context["degrees"] = degrees
#		return context
#

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class IndexListView(SingleTableMixin, FilterView):
    table_class = PaperTable
    model = Paper
    template_name = "papers/index.html"

    filterset_class = PapersFilter


#class IndexListView(SingleTableView):
#    model = Paper
#    table_class = PaperTable
#    template_name = 'papers/index.html'

class PaperListView(generic.ListView):
    template_name = 'papers/papers_list.html'
    context_object_name = 'papers'
    model = Paper
    paginate_by = 5
    ordering = ['title']
    
    def get_queryset(self):
        order = self.request.GET.get('orderby', 'title')
        d_or_a = self.request.GET.get('desc_or_asc', '')
        return super().get_queryset().all().order_by(f'{d_or_a}{order}')
    

    def get_context_data(self, **kwargs):
        context = super(PaperListView, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby', 'title')
        context['desc_or_asc'] = self.request.GET.get('desc_or_asc', '')
        return context
	
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get("paginate_by", self.paginate_by)
    


class PaperDetailView(generic.DetailView):
    model = Paper
    template_name = "papers/paper_detail.html"
    context_object_name = 'paper'


class PaperCreateView(LoginRequiredMixin,generic.CreateView):
    template_name = "papers/create_paper.html"
    form_class = PaperModelForm

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "You have successfully created a paper")
        return super(PaperCreateView, self).form_valid(form)


class PaperUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    template_name = "papers/update_paper.html"
    form_class = PaperModelForm
    def get_queryset(self):
        return Paper.objects.all()

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this paper")
        return super(PaperUpdateView, self).form_valid(form)


class PaperDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name = "papers/delete_paper.html"
    context_object_name = "paper"


    def get_success_url(self):
        return reverse("papers:index")

    def get_queryset(self):
        return Paper.objects.all()




class ResearcherListView(generic.ListView):
    template_name = 'papers/researchers_list.html'
    context_object_name = 'researchers'
    model = Researcher
    paginate_by = 10
    ordering = ['first_name', 'second_name', 'third_name', 'fourth_name', 'alternative_name']
    
    def get_queryset(self):
        return super().get_queryset().all()

    def get_context_data(self, **kwargs):
        context = super(ResearcherListView, self).get_context_data(**kwargs)
        return context
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get("paginate_by", self.paginate_by)


class ResearcherDetailView(generic.DetailView):
    model = Researcher
    template_name = "papers/researcher_detail.html"
    context_object_name = 'researcher'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        papers = Paper.objects.all()
        
        context["papers"] = papers
        return context


class ResearcherCreateView(LoginRequiredMixin,generic.CreateView):
    template_name = "papers/create_researcher.html"
    form_class = ResearcherModelForm

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "You have successfully created a researcher")
        return super(ResearcherCreateView, self).form_valid(form)


class ResearcherUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    template_name = "papers/update_researcher.html"
    form_class = ResearcherModelForm
    def get_queryset(self):
        return Researcher.objects.all()

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this researcher")
        return super(ResearcherUpdateView, self).form_valid(form)


class ResearcherDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name = "papers/delete_researcher.html"
    context_object_name = "researcher"

    def get_success_url(self):
        return reverse("papers:index")

    def get_queryset(self):
        return Researcher.objects.all()



class SupervisorListView(generic.ListView):
    template_name = 'papers/supervisors_list.html'
    context_object_name = 'supervisors'
    model = Supervisor
    paginate_by = 10
    ordering = ['first_name', 'second_name', 'third_name', 'fourth_name', 'alternative_name']
    
    def get_queryset(self):
        return super().get_queryset().all()

    def get_context_data(self, **kwargs):
        context = super(SupervisorListView, self).get_context_data(**kwargs)
        return context
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get("paginate_by", self.paginate_by)


class SupervisorDetailView(generic.DetailView):
    model = Supervisor
    template_name = "papers/supervisor_detail.html"
    context_object_name = 'supervisor'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        papers = Paper.objects.all()
        
        context["papers"] = papers
        return context



class SupervisorCreateView(LoginRequiredMixin,generic.CreateView):
    template_name = "papers/create_supervisor.html"
    form_class = SupervisorModelForm

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "You have successfully created a supervisor")
        return super(SupervisorCreateView, self).form_valid(form)


class SupervisorUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    template_name = "papers/update_supervisor.html"
    form_class = SupervisorModelForm
    def get_queryset(self):
        return Supervisor.objects.all()

    def get_success_url(self):
        return reverse("papers:index")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this Supervisor")
        return super(SupervisorUpdateView, self).form_valid(form)


class SupervisorDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name = "papers/delete_supervisor.html"
    context_object_name = "supervisor"
    
    def get_success_url(self):
        return reverse("papers:index")

    def get_queryset(self):
        return Supervisor.objects.all()



#
#class PaperUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
#    template_name = "leads/lead_update.html"
#    form_class = PaperModelForm
#
#    def get_queryset(self):
#        user = self.request.user
#        # initial queryset of leads for the entire organisation
#        return Paper.objects.filter(organisation=user.userprofile)
#
#    def get_success_url(self):
#        return reverse("Papers:Papers-list")
#
#    def form_valid(self, form):
#        form.save()
#        messages.info(self.request, "You have successfully updated this lead")
#        return super(PaperUpdateView, self).form_valid(form)
#
#
#

#
#
#class LandingPageView(generic.TemplateView):
#    template_name = "index.html"
#    def get_context_data(self, **kwargs):
#		context = super().get_context_data(**kwargs)
#        papers = Paper.objects.all()
#        context["papers"] = papers
#        return context

papers/templates/papers/paper_detail.html
{% extends 'layout.html' %}

{% block content %}
<div class="papers-table" dir="rtl">
    <table>
        <tr class="heading" >
            <td class="title" >العنوان</td>
            <td class="researcher"> الباحث</td>
            <td class="supervisor"> المشرف</td>
            <td class="degree">الدرجة العلمية</td>
            <td class="date">تاريخ النشر</td>
            <td class="number">رقم الورقة</td>
            <td class="links">#</td>
        </tr>


				<tr class="details">
					<td class="title">{{paper.title}}</td>
					<td class="researcher"><a href="{% url 'papers:researcher_detail' paper.researcher.pk %}">{{paper.researcher}}</a></td>
                    <td class="supervisor">
                    {% for papersupervisor in paper.supervisor.all %}
                    <a href="{% url 'papers:supervisor_detail' papersupervisor.pk %}" >
					{{papersupervisor}}</a><br>
                    
                    {% endfor %}
                    </td>
					<td class="degree">{{paper.degree}}</td>
					<td class="date_of_publishing">{{paper.date_of_publishing}}</td>
					<td class="number">{{paper.paper_number}}</td>
					<td class="links">
                        <a href="{% url 'papers:update_paper' paper.pk %}" >تعديل الورقة</a>\
                        <a href="{% url 'papers:update_researcher' paper.researcher.pk %}" >تعديل الباحث</a>\
                        {% for papersupervisor in paper.supervisor.all %}
                            <a href="{% url 'papers:update_supervisor' papersupervisor.pk %}" >تعديل المشرف</a>\
                        {% endfor %}
                        <a href="{% url 'papers:delete_paper' paper.pk %}" >إزالة الورقة</a>
                    </td>
				</tr>
            
        </table>
    </div>
    {% endblock %}

papers/templates/papers/papers_list.html
{% extends 'layout.html' %}

{% block content %}
<center>
<div class="create_new">
    <a class="btn btn-outline-primary" href="{% url 'papers:create_paper' %}" >إضافة ورقة جديدة</a>
    <a class="btn btn-outline-primary" href="{% url 'papers:create_supervisor' %}" >إضافة مشرف جديد</a>
    <a class="btn btn-outline-primary" href="{% url 'papers:create_researcher' %}" >إضافة باحث جديد</a>
</div>
</center>
<div class="papers-table" dir="rtl">
    

    <table>
        <tr class="heading" >
            <td class="title" >العنوان</td>
            <td class="researcher"> الباحث</td>
            <td class="supervisor"> المشرف</td>
            <td class="degree">الدرجة العلمية</td>
            <td class="date">تاريخ النشر</td>
            <td class="number">رقم الورقة</td>
            <td class="links">#</td>
        </tr>
{% for paper in papers %}

				<tr class="details">
					<td class="title"><a href="{% url 'papers:paper_detail' paper.pk %}">{{paper.title}}</a></td>
					<td class="researcher"><a href="{% url 'papers:researcher_detail' paper.researcher.pk %}">{{paper.researcher}}</a></td>
                    <td class="supervisor">
                    {% for papersupervisor in paper.supervisor.all %}
                    <a href="{% url 'papers:supervisor_detail' papersupervisor.pk %}" >
					{{papersupervisor}} </a><br>
                    
                    {% endfor %}
                    </td>
					<td class="degree">{{paper.degree}}</td>
					<td class="date_of_publishing">{{paper.date_of_publishing}}</td>
					<td class="number">{{paper.paper_number}}</td>
					<td class="links">
                        <a href="{% url 'papers:update_paper' paper.pk %}" >تعديل الورقة</a>
                        <a href="{% url 'papers:update_researcher' paper.researcher.pk %}" >تعديل الباحث</a>
                        {% for papersupervisor in paper.supervisor.all %}
                            <a href="{% url 'papers:update_supervisor' papersupervisor.pk %}" >تعديل المشرف</a>
                        {% endfor %}
                    </td>
				</tr>
            {% endfor %}

{% if is_paginated %}

<br>
<div class="paper-navegation">
    <form method="GET">
        <select name="paginate_by" class="btn btn-outline-info">
            <option value="none" selected disabled hidden>إختر عدد الأوراق لكل صفحة</option>
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
            
        </select>
        <select name="orderby" class="btn btn-outline-info">
            <option value="none" selected disabled hidden>إختر خانة الترتيب</option>
            <option value="title" >العنوان</option>
            <option value="researcher">الباحث</option>
            <option value="degree">الدرجة العلمية</option>
            <option value="date_of_publishing">تاريخ النشر</option>
            <option value="paper_number">رقم الورقة</option>
            
        </select>
        <select name="desc_or_asc" class="btn btn-outline-info">
            <option value="none" selected disabled hidden>إختر الترتيب</option>
            <option value="" >ASC</option>
            <option value="-">DESC</option>
        </select>
        <input type="submit" value="إختر" class="btn btn-primary" > 
    </form>
<br>
<br>
    

                
            </div>
        </table>
        <br>
        {% firstof request.GET.paginate_by "5" as paginate_by %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">الأولى</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">السابقة</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">{{num}}</a>
        {% endif %}
    {% endfor %}
    {%if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">التالية</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}&paginate_by={{ paginate_by }}&orderby={{orderby}}&desc_or_asc={{desc_or_asc}}">الأخيرة</a>
    {% endif %}
</div>
{% endif %}
    </div>
        
        
        

{% endblock %}

papers/templates/papers/researcher_detail.html
{% extends 'layout.html' %}

{% block content %}
<div class="papers-table" dir="rtl">
    <table>
        <tr class="heading" >
            <td class="first_name" >الإسم الأول</td>
            <td class="second_name"> الإسم الثاني</td>
            <td class="third_name"> الإسم الثالث</td>
            <td class="fourth_name">الإسم الرابع</td>
            
            
            <td class="links">#</td>
            
        </tr>


                <tr class="details">
                    <td class="first_name">{{researcher.first_name}}</td>
                    <td class="second_name">{{researcher.second_name}}</td>
                    <td class="third_name">{{researcher.third_name}}</td>
                    <td class="fourth_name">{{researcher.fourth_name}}</td>
                    
                    <td class="links">
                        <a href="{% url 'papers:update_researcher' researcher.pk %}" >تعديل الباحث</a>/
                        <a href="{% url 'papers:delete_researcher' researcher.pk %}" >إزالة الباحث</a>
                    </td>
                </tr>
            
            </table>
        </div>

        <div class="papers-table" dir="rtl">
            <table>
                <tr class="heading" >
                    <td class="title" >العنوان</td>
                    <td class="researcher"> الباحث</td>
                    <td class="supervisor"> المشرف</td>
                    <td class="degree">الدرجة العلمية</td>
                    <td class="date">تاريخ النشر</td>
                    <td class="number">رقم الورقة</td>
                    <td class="links">#</td>
                </tr>
        {% for paper in papers %}
        
        {% if paper.researcher == researcher %}
                        <tr class="details">
                            <td class="title"><a href="{% url 'papers:paper_detail' paper.pk %}">{{paper.title}}</a></td>
                            <td class="researcher">{{paper.researcher}}</td>
                            <td class="supervisor">
                            {% for papersupervisor in paper.supervisor.all %}
                            
                            <a href="{% url 'papers:supervisor_detail' papersupervisor.pk %}" >{{papersupervisor}} </a><br>
                            
                            {% endfor %}
                            </td>
                            <td class="degree">{{paper.degree}}</td>
                            <td class="date_of_publishing">{{paper.date_of_publishing}}</td>
                            <td class="number">{{paper.paper_number}}</td>
                            <td class="links">
                                <a href="{% url 'papers:update_paper' paper.pk %}" >تعديل الورقة</a>
                                {% for papersupervisor in paper.supervisor.all %}
                                <a href="{% url 'papers:update_supervisor' papersupervisor.pk %}" >تعديل المشرف</a>
                                {% endfor %}
                        </tr>
                        {% endif %}

                    
                    {% endfor %}
                    
                </table>
            </div>
        
            {% for paper in papers %}
            {% for papersupervisor in paper.supervisor.all %}
            {% if researcher.first_name == papersupervisor.first_name and researcher.second_name == papersupervisor.second_name and researcher.third_name == papersupervisor.third_name and researcher.fourth_name == papersupervisor.fourth_name %}
        
        <div class="papers-table" dir="rtl">
            <h4>من البحوث التي أشرف عليها </h4>
            <table>
                <tr class="heading" >
                    <td class="title" >العنوان</td>
                    <td class="researcher"> الباحث</td>
                    <td class="supervisor"> المشرف</td>
                    <td class="degree">الدرجة العلمية</td>
                    <td class="date">تاريخ النشر</td>
                    <td class="number">رقم الورقة</td>
                    <td class="links">#</td>
                </tr>
       
                        <tr class="details">
                            <td class="title"><a href="{% url 'papers:paper_detail' paper.pk %}">{{paper.title}}</a></td>
                            <td class="researcher">{{paper.researcher}}</td>
                            <td class="supervisor">
                            {% for papersupervisor2 in paper.supervisor.all %}
                            
                            {{papersupervisor2}} <br>
                            
                            {% endfor %}
                            </td>
                            <td class="degree">{{paper.degree}}</td>
                            <td class="date_of_publishing">{{paper.date_of_publishing}}</td>
                            <td class="number">{{paper.paper_number}}</td>
                            <td class="links">
                                <a href="{% url 'papers:update_paper' paper.pk %}" >تعديل الورقة</a>
                                <a href="{% url 'papers:update_researcher' paper.researcher.pk %}" >تعديل الباحث</a>
                                {% for papersupervisor in paper.supervisor.all %}
                                    <a href="{% url 'papers:update_supervisor' papersupervisor.pk %}">تعديل المشرف</a>
                                {% endfor %}
                            </td>
                        </tr>
                        

                    
                </table>
            </div>
            {% endif %}

                    {% endfor %}
                    {% endfor %}
{% endblock content %}